<?php
/**
 * Script: Lokalisasi Google Fonts untuk Laravel
 * 
 * Jalankan dari root project Laravel:
 *   php localize-fonts.php
 * 
 * Script ini akan:
 *  1. Download file .woff2 Outfit & DM Sans dari Google Fonts
 *  2. Simpan ke public/fonts/
 *  3. Generate public/css/fonts.css dengan @font-face lokal
 */

$ua = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

$fontDir = __DIR__ . '/public/fonts';
$cssDir  = __DIR__ . '/public/css';

@mkdir($fontDir, 0755, true);
@mkdir($cssDir,  0755, true);

// Font yang akan didownload
$fonts = [
    [
        'family'   => 'Outfit',
        'weights'  => [600, 700, 800],
        'url'      => 'https://fonts.googleapis.com/css2?family=Outfit:wght@600;700;800&display=swap',
        'prefix'   => 'outfit',
    ],
    [
        'family'   => 'DM Sans',
        'weights'  => [400, 500, 600],
        'url'      => 'https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600&display=swap',
        'prefix'   => 'dmsans',
    ],
];

$fontFaces = [];
$downloaded = 0;

foreach ($fonts as $font) {
    echo "Fetching CSS for {$font['family']}...\n";

    $ctx = stream_context_create(['http' => ['header' => "User-Agent: $ua\r\n"]]);
    $css = @file_get_contents($font['url'], false, $ctx);

    if (!$css) {
        echo "  ERROR: Gagal fetch CSS. Cek koneksi internet.\n";
        continue;
    }

    // Ekstrak semua blok @font-face
    preg_match_all('/@font-face\s*\{([^}]+)\}/s', $css, $blocks);

    foreach ($blocks[1] as $block) {
        // Ambil font-weight
        preg_match('/font-weight:\s*(\d+)/', $block, $wm);
        $weight = $wm[1] ?? '400';

        // Ambil URL woff2
        preg_match('/url\(([^)]+\.woff2)\)/', $block, $um);
        $woff2url = trim($um[1] ?? '', "'\"");

        if (!$woff2url) continue;

        $filename = $font['prefix'] . '-' . $weight . '.woff2';
        $filepath = $fontDir . '/' . $filename;
        $webpath  = '/fonts/' . $filename;

        // Download file .woff2
        if (!file_exists($filepath)) {
            echo "  Downloading {$filename}...\n";
            $data = @file_get_contents($woff2url, false, $ctx);
            if ($data) {
                file_put_contents($filepath, $data);
                $downloaded++;
                echo "  ✓ Saved: {$filename} (" . round(strlen($data)/1024) . " KB)\n";
            } else {
                echo "  ✗ Gagal download: {$woff2url}\n";
                continue;
            }
        } else {
            echo "  ✓ Skip (sudah ada): {$filename}\n";
        }

        // Ambil unicode-range
        preg_match('/unicode-range:\s*([^;]+);/', $block, $ucm);
        $unicodeRange = trim($ucm[1] ?? 'U+0000-00FF');

        $fontFaces[] = "@font-face {
  font-family: '{$font['family']}';
  font-style: normal;
  font-weight: {$weight};
  font-display: swap;
  src: url('{$webpath}') format('woff2');
  unicode-range: {$unicodeRange};
}";
    }
}

// Tulis fonts.css
$cssContent = "/* Local fonts – generated by localize-fonts.php */\n/* Menggantikan Google Fonts untuk performa lebih baik */\n\n";
$cssContent .= implode("\n\n", $fontFaces) . "\n";

file_put_contents($cssDir . '/fonts.css', $cssContent);

echo "\n✓ Selesai! $downloaded file font didownload.\n";
echo "✓ CSS disimpan ke: public/css/fonts.css\n\n";
echo "===========================================\n";
echo "LANGKAH SELANJUTNYA:\n";
echo "===========================================\n";
echo "Ganti baris ini di SEMUA file blade:\n\n";
echo "  HAPUS:\n";
echo "    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\n";
echo "    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\n";
echo "    <link href=\"https://fonts.googleapis.com/css2?...\" rel=\"stylesheet\">\n\n";
echo "  GANTI DENGAN:\n";
echo "    <link rel=\"stylesheet\" href=\"/css/fonts.css\">\n\n";
echo "File blade yang perlu diubah:\n";
echo "  - resources/views/inventory/public.blade.php\n";
echo "  - resources/views/home.blade.php (halaman jadwal)\n";
echo "  - resources/views/rekap/public.blade.php\n";
echo "  - resources/views/assignment/public.blade.php\n";
echo "  (dan file blade lain yang load Google Fonts)\n";